export const RegisterFormFields = [
    {
        label: "First Name",
        name: "firstName",
        type: "text",
        autoComplete: "given-name",
        width: "50%",
    },
    {
        label: "Last Name",
        name: "lastName",
        type: "text",
        autoComplete: "family-name",
        width: "50%",
    },
    {
        label: "Username",
        name: "username",
        type: "text",
        autoComplete: "username",
        width: "100%",
    },
    {
        label: "Email",
        name: "email",
        type: "email",
        autoComplete: "email",
        width: "100%",
    },
    {
        label: "Password",
        name: "password",
        type: "password",
        autoComplete: "new-password",
        width: "100%",
    },
    {
        label: "Confirm Password",
        name: "confirmPassword",
        type: "password",
        autoComplete: "new-password",
        width: "100%",
    },
    {
        label: "Phone",
        name: "phone",
        type: "tel",
        autoComplete: "tel",
        width: "50%",
    },
    {
        label: "Zipcode",
        name: "zipcode",
        type: "text",
        autoComplete: "postal-code",
        width: "50%",
    },
    {
        label: "Address",
        name: "address",
        type: "text",
        autoComplete: "street-address",
        width: "100%",
    },
];