import type { DynamicFormField } from "../../../../interfaces/form.interface";

export const userFormConfig: DynamicFormField[] = [
    {
        name: "first_name",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        gridClass: "half",
        rules: { required: "First name is required" },
        validationMessages: { required: "First name is required" },
    },
    {
        name: "last_name",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        gridClass: "half",
        rules: { required: "Last name is required" },
        validationMessages: { required: "Last name is required" },
    },
    {
        name: "username",
        label: "Username",
        type: "text",
        placeholder: "Choose a username",
        gridClass: "half",
        rules: { required: "Username is required" },
        validationMessages: { required: "Username is required" },
    },
    {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "Enter email address",
        gridClass: "half",
        rules: { required: "Email is required" },
        validationMessages: { required: "Email is required" },
    },
    // ───────────────── Country / State / City ─────────────────
    {
        name: "country",
        label: "Country",
        type: "country-select",
        placeholder: "Select country",
        gridClass: "half",
        rules: { required: "Country is required" },
        validationMessages: { required: "Country is required" },
    },
    {
        name: "state",
        label: "State",
        type: "state-select",
        placeholder: "Select state",
        gridClass: "half",
        rules: { required: "State is required" },
        validationMessages: { required: "State is required" },
    },
    {
        name: "city",
        label: "City",
        type: "city-select",
        placeholder: "Select city",
        gridClass: "half",
        rules: { required: "City is required" },
        validationMessages: { required: "City is required" },
    },

    // ───────────────── Phone ─────────────────
    {
        name: "phone",
        label: "Phone",
        type: "phone",
        placeholder: "Enter phone number",
        gridClass: "half",
        rules: {},
        validationMessages: {},
    },

    // ───────────────── Address Details ─────────────────
    {
        name: "address",
        label: "Address",
        type: "text",
        placeholder: "Enter street address",
        gridClass: "full",
        rules: {},
        validationMessages: {},
    },
    {
        name: "zipcode",
        label: "Zip Code",
        type: "text",
        placeholder: "Enter zip code",
        gridClass: "half",
        rules: {},
        validationMessages: {},
    },

    // ───────────────── Role & Employment ─────────────────
    {
        name: "role_id",
        label: "Role",
        type: "select",
        placeholder: "Select role",
        gridClass: "half",
        rules: { required: "Role is required" },
        validationMessages: { required: "Role is required" },
        options: [
            { label: "Admin", value: 1 },
            { label: "User", value: 2 },
            { label: "Manager", value: 3 },
        ],
    },
    {
        name: "employment_start_date",
        label: "Employment Start Date",
        type: "date",
        placeholder: "Select start date",
        gridClass: "half",
        rules: {},
        validationMessages: {},
    },
    {
        name: "date_of_birth",
        label: "Date of Birth",
        type: "date",
        placeholder: "Select date of birth",
        gridClass: "half",
        rules: {},
        validationMessages: {},
    },
    {
        name: "position",
        label: "Position",
        type: "text",
        placeholder: "Enter job position",
        gridClass: "half",
        rules: {},
        validationMessages: {},
    },
];
